version: '3'

services:
  
  tplus_frontend:
    container_name: tplus_frontend
#    build: ./
    image: ghcr.io/sahanlk/tutor_plus_frontend:${IMAGE_TAG}
    restart: always
    ports:
      - "3000:3000"
    networks:
      - tplus_network

networks:
  tplus_network:
    external: true
