import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import React from "react";
import ReduxProvider from "@/lib/store/ReduxProvider";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});


export const metadata: Metadata = {
    title: "Tutor Plus",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`${inter.variable} max-w-screen mx-auto`}>
        <ReduxProvider>
        <Navbar/>
        <div className="content-inner top-3 mt-20 py-12 min-h-screen">
            {children}
        </div>
        </ReduxProvider>
        <Footer/>
        </body>
        </html>
    );
}
