import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer";
import React from "react";
import ReduxProvider from "@/lib/store/ReduxProvider";
import TokenRefresher from "@/components/TokenRefresher";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});


export const metadata: Metadata = {
    title: "Tutor Plus",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} max-w-screen mx-auto bg-gray-100`}>
                <ReduxProvider>
                    <TokenRefresher />
                    <Navbar />
                    <div className="content-inner">
                        {children}
                    </div>
                </ReduxProvider>
                <Footer />
            </body>
        </html>
    );
}
