import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`${inter.variable} antialiased max-w-screen mx-auto px-4`}>
        <Navbar/>
        <div className="content-inner top-3 mt-20">
            {children}
        </div>
        <Footer/>
        </body>
        </html>
    );
}
